config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'places#index'
  resources :places do
    resources :comments, only: :create
    resources :photos, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :place
  after_create :send_comment_email

  RATINGS = {
   'one star'    => '1_star',
   'two stars'   => '2_stars',
   'three stars' => '3_stars',
   'four stars'  => '4_stars',
   'five stars'  => '5_stars'
 }

 def humanized_rating
    RATINGS.invert[self.rating]
  end

  def send_comment_email
      NotificationMailer.comment_added(self).deliver
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place
  belongs_to :user
  mount_uploader :picture, PictureUploader
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true,
    length: {
      maximum: 76,
      minimum: 3,
      too_long: "%{count} characters is the maximum number of characters allowed",
      too_short: "Must be at least %{count} characters long" }
  validates :address, presence: true
  validates :description, presence: true,
    length: {
    maximum: 1000,
    minimum: 3,
    too_long: "%{count} characters is the maximum number of characters allowed",
    too_short: "Must be at least %{count} characters long" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :places, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :photos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
   @place = Place.find(params[:place_id])
   @place.comments.create(comment_params.merge(user: current_user))
   redirect_to place_path(@place)
 end

  private

  def comment_params
    params.require(:comment).permit(:message, :rating)
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  def create
   @place = Place.find(params[:place_id])
   @place.photos.create(photo_params.merge(user: current_user))
   if @place.valid?
     redirect_to place_path(@place)
   else
     render :new, status: :unprocessable_entity
   end
 end


  private

  def photo_params
    params.require(:photo).permit(:caption, :picture)
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @places = Place.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 7)
  end

  def new
    @place = Place.new
  end

  def create
    @place = current_user.places.create(place_params)
    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @place = Place.find(params[:id])
    @comment = Comment.new
    @photo = Photo.new
  end

  def edit
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Oh No! Only the user who created a place is able to update it.', status: :forbidden
    end
  end

  def update
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Oh No! Only the user who created a place is able to update it.', status: :forbidden
    end

    @place.update_attributes(place_params)

    if @place.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @place = Place.find(params[:id])

    if @place.user != current_user
      return render text: 'Oh No! Only the user who created a place is able to delete it.', status: :forbidden
    end

    @place.destroy
    redirect_to root_path
  end

  private

  def place_params
    params.require(:place).permit(:name, :description, :address)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nomster</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- nav goes here -->
    <%= render "shared/menu" %>

    <!-- flash notices-->
    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <!-- main page content -->
    <%= yield %>
    
  </body>
</html>

app/views/places/_form.html.erb
<%= simple_form_for @place do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <br/>
  <%= f.submit 'Place Place', class: 'btn btn-primary' %>
<% end %>

app/views/places/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Edit The Place Details</h1>
  <%= render "form" %>
</div>

app/views/places/index.html.erb
<div id="nomster-carousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#nomster-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#nomster-carousel" data-slide-to="1"></li>
    <li data-target="#nomster-carousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item">
      <%= image_tag 'friends-food.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Discover the best brunch.
      </div>
    </div>
    <div class="item">
      <%= image_tag 'coffee.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Uncover the best coffee nook.
      </div>
    </div>
    <div class="item active">
      <%= image_tag 'pizza.jpeg', class: 'img-responsive' %>
      <div class="carousel-caption">
        Find your favorite slice.
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#nomster-carousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#nomster-carousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<% @places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />

    <% if place.user.present? %>
      <small><%= place.user.email %></small>
    <% end %>
    <% if place.comments.present? %>
      <div class="col-xs-10 col-xs-offset-1 comments">
        <blockquote>
          <% if place.comments.last.humanized_rating.present? %>
            <b><%= place.comments.last.humanized_rating %></b> -
          <% end %>
          <%= place.comments.last.message %>
          <small><%= place.comments.last.user.email %></small>
        </blockquote>
      </div>
    <% end %>
  </div>
<% end %>
<div class="col-xs-12 center-flex-containter">
  <%= will_paginate @places %>
</div>

app/views/places/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Enter Your Place Details</h1>
  <%= simple_form_for @place do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <br/>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="booyah-box col-xs-8 col-xs-offset-2">
  <h1><%= @place.name %></h1>
  <i><%= @place.address %></i>
  <br/><br/>
  <p><%= @place.description %></p>

  <% if @place.latitude.present? && @place.longitude.present? %>
    <script>

      function initMap() {
        var markerLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};

        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 12,
          center: markerLatLng
        });

        var marker = new google.maps.Marker({
          position: markerLatLng,
          map: map,
          title: '<%= @place.name %>'
        });
      }
    </script>

    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAAdxvEXEwebipdOCtmD9P1OtId4TaVvcA&callback=initMap">
    </script>

    <div id="map"></div>

  <% end %>
  <br/>

  <div class="pull-right">
    <% if current_user && current_user == @place.user %>
      <%= link_to 'Edit', edit_place_path(@place), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', place_path(@place), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger' %>
    <% end %>
      <%if @place.photos.none? & current_user %>
        <button class="btn btn-success btn-lg center" data-toggle="modal" data-target="#photoModal">
          Add a Photo!
      </button>
    <% end %>
    <%if @place.comments.none? & current_user %>
      <button class="btn btn-primary btn-lg center" data-toggle="modal" data-target="#commentModal">
        Add a Comment!
      </button>
    <% end %>
  </div>

</div>

<div class="clear"></div>

<% if @place.comments.present? %>
  <div class="col-xs-6 col-xs-offset-3">
    <br/>
    <h2>Comments</h2>
    <br/>

    <% @place.comments.each do |comment| %>
      <div>
        <blockquote>
          <% if comment.humanized_rating.present? %>
            <b><%= comment.humanized_rating %></b> -
          <% end %>
          <%= comment.message %>
          <small><%= comment.user.email %></small>
        </blockquote>
      </div>
    <% end %>

    <%if current_user %>
      <button class="btn btn-primary btn-lg center" data-toggle="modal" data-target="#commentModal">
          Add a Comment!
      </button>
    <% end %>

  </div>
<% end %>

<%if @place.photos.any? %>
<div class="photos-container booyah-box col-xs-6 col-xs-offset-3">
  <h2>   Photos of <%= @place.name %></h2>
  <% @place.photos.each do |photo| %>
    <br/>
    <div class="photo">
      <%= image_tag photo.picture, :class => 'img-responsive' %>
      <br/>
      <h5> -- <%= photo.caption %></h5>
      <h6> Sumbitted by <%= photo.user.email %></h6>
      <br/>
    </div>
  <% end %>
  <%if current_user %>
    <button class="btn btn-success btn-lg center" data-toggle="modal" data-target="#photoModal">
      Add a Photo!
    </button>
  <% end %>

</div>
<% end %>

  <!-- Comment Modal -->
  <div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="commentModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="commentModalLabel">Add a comment</h4>
        </div>
        <%= simple_form_for @comment, url: place_comments_path(@place) do |f| %>
         <div class="modal-body">
           <%= f.input :message %>
           <%= f.input :rating, as: :select, collection: Comment::RATINGS %>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
         </div>
       <% end %>
      </div>
    </div>
  </div>

  <!-- Photo Modal -->
  <div class="modal fade" id="photoModal" tabindex="-1" role="dialog" aria-labelledby="photoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="photoModalLabel">Add a Photo</h4>
        </div>
        <%= simple_form_for @photo, url: place_photos_path(@place) do |f| %>
         <div class="modal-body">
           <%= f.file_field :picture %>
           <%= f.input :caption %>
         </div>
         <div class="modal-footer">
           <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
           <%= f.submit "Add a Photo", class: 'btn btn-primary' %>
         </div>
       <% end %>
      </div>
    </div>
  </div>

<br/><br/>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Nomster', root_path, class: 'navbar-brand' %>
    </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to new_place_path do %>
            <i class="glyphicon glyphicon-plus-sign"></i>
            New Place
          <% end %>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
           <li>
             <%= link_to 'My Profile', user_path(current_user) %>
           </li>
           <li>
             <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
           </li>
        <% else %>
          <li>
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
          <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/show.html.erb
<div class="booyah-box col-xs-12 col-sm-8 col-sm-offset-2">
  <div class="col-xs-4">
    <%= image_tag 'user.png' %>
  </div>

  <div class="col-xs-8">
    <h1><%= @user.email %></h1>
    <h3>Member Since: <%= @user.created_at.strftime("%B %d, %Y") %></h3>
    <h4><%= @user.comments.count %> total comments</h4>
    <h4><%= @user.comments.where(rating: '5_stars').count %> total 5 star reviews</h4>
  </div>
  <div class="clear"></div>
</div>
<div class="clear"></div>
<% if @user.comments.any? %>
  <br /><br />
  <h1 class="text-center">My Comments</h1>
  <br /><br />
  <% @user.comments.each do |comment| %>
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h2 class="text-center"><%= link_to comment.place.name, place_path(comment.place) %></h2>

      <blockquote>
        <% if comment.humanized_rating.present? %>
          <b><%= comment.humanized_rating %></b> -
        <% end %>
        <%= comment.message %>
        <small><%= comment.user.email %></small>
      </blockquote>
    </div>
  <% end %>
<% end %>

<div class="clear"></div>

<% if @user.places.any? %>
  <h1 class="text-center">My Places</h1>
  <% @user.places.each do |place| %>
  <div class="booyah-box col-xs-10 col-xs-offset-1">
    <h1><%= link_to place.name, place_path(place) %></h1><br />
    <i><%= place.address %></i><br /><br />
    <p><%= place.description %></p><br />
  </div>
  <% end %>
<% end %>